language: elixir
elixir: 1.2.3
otp_release: 18.3
sudo: false
addons:
  postgresql: "9.4"
script:
  - mix test --include integration
  - MIX_ENV=test mix run scripts/sample_data.exs
notifications:
  recipients:
    - eric.meadows.jonsson@gmail.com
